using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Sample
{
    public class CGoal
    {
        public List<string> Motivations = new List<string>();




        public CGoal()
        {
            if (Motivations == null)
            {
                Motivations = new List<string>();
            }
            InitializeMotivations();
        }

        public void InitializeMotivations()
        {
            string res = "Assassinate the King: to avoid ware the king is hell-bent on starting";
            Motivations.Add(res);
            res = "Assassinate the King: to get the king's successor, your friend, on the throne.";
            Motivations.Add(res);
            res = "Get accepted into a prestigious college: to make the bullies you went to school with jealous.";
            Motivations.Add(res);
            res = "Get accepted into a prestigious college: to finally win your father's approval.";
            Motivations.Add(res);
            res = "Get a new job: to escape a mean boss";
            Motivations.Add(res);
            res = "Get a new job: to escape an unpleasant coworker";
            Motivations.Add(res);
            res = "Get a new job: to actually work in your chosen field.";
            Motivations.Add(res);
            res = "Make a fortune: to impress the person you're in love with, who is very high-class";
            Motivations.Add(res);
            res = "Make a fortune: to have the means to exact revenge on your enemies.";
            Motivations.Add(res);
            res = "Make a fortune: to make sure your parents, siblings, or children never have to worry about money again.";
            Motivations.Add(res);
            res = "Move to New York City or to Paris: to experience the glamorous, big-city life you've always dreamed of";
            Motivations.Add(res);
            res = "Move to New York City or to Paris: to create a new identity for yourself where nobody knows you, so you can escape the people who want you dead";
            Motivations.Add(res);
            res = "Journey to a faraway country…or planet: to establish a new settlement away from a dying planet or an oppressive regime.";
            Motivations.Add(res);
            res = "Journey to a faraway country…or planet: to become famous for exploration, which makes you feel important.";
            Motivations.Add(res);
            res = "Journey to a faraway country…or planet: to conduct research on behalf of your government and satisfy your own curiosity in the process.";
            Motivations.Add(res);
            res = "Journey to a faraway country…or planet: to establish a new colony and to expand the country's empire, satisfying your nationalistic zeal in the process.";
            Motivations.Add(res);
            res = "Journey to a faraway country…or planet: to satisfy your extreme and perhaps unfortunate desire for adventure and danger.";
            Motivations.Add(res);
            res = "Journey to a faraway country…or planet: to get far away from the person who broke your heart.";
            Motivations.Add(res);
            res = "Return to hometown: to help out an ailing or aging relative.";
            Motivations.Add(res);
            res = "Return to hometown: to move in with a relative or friend because you're down on your luck.";
            Motivations.Add(res);
            res = "Adopt a dog: to have some company because you're lonely.";
            Motivations.Add(res);
            res = "Adopt a dog: to have a guard dog because you don't feel safe living on your own.";
            Motivations.Add(res);
            res = "Adopt a dog: to keep the dog from being euthanized at the shelter.";
            Motivations.Add(res);
            res = "Lose weight: to look good for an upcoming wedding, vacation, or special event.";
            Motivations.Add(res);
            res = "Lose weight: to lower your risk of heart disease.";
            Motivations.Add(res);
            res = "Learn how to do yoga: to deal with stress in a healthy way.";
            Motivations.Add(res);
            res = "Learn how to do yoga: to feel younger and more nimble.";
            Motivations.Add(res);
            res = "Get elected to public office: to pass important legislation that would've helped one of your family members.";
            Motivations.Add(res);
            res = "Get elected to public office: to use the position to make more money for your businesses.";
            Motivations.Add(res);
            res = "Create something artistic, such as a painting or a screenplay: to depict a real person, either to honor or disparage them.";
            Motivations.Add(res);
            res = "Create something artistic, such as a painting or a screenplay: to make people see the truth about a situation or issue.";
            Motivations.Add(res);
            res = "Create something artistic, such as a painting or a screenplay: to bring more joy to a specific person or group of people... or the world.";
            Motivations.Add(res);
            res = "Figure out who the killer is: to prove a wrongfully accused person (family member, romantic interest, or close friend) innocent.";
            Motivations.Add(res);
            res = "Figure out who the killer is: to get justice because the victim was a family member, romantic interest, or close friend.";
            Motivations.Add(res);
            res = "Figure out who the killer is: to give them a reward -- the person they killed was actually a monster.";
            Motivations.Add(res);
            res = "Get married: to avoid living alone.";
            Motivations.Add(res);
            res = "Get married: to start a family.";
            Motivations.Add(res);
            res = "Get married: to find someone to help you take care of children you already have.";
            Motivations.Add(res);
            res = "Get married: to get on someone else's insurance.";
            Motivations.Add(res);
            res = "Get married: to let someone get on your insurance.";
            Motivations.Add(res);
            res = "Start a small business: to be able to work in your hometown, close to family.";
            Motivations.Add(res);
            res = "Start a small business: to survive -- no other company will hire you.";
            Motivations.Add(res);
            res = "Start a small business: to do what you're best at and to feel the most passionate about, every day.";
            Motivations.Add(res);
            res = "Get a divorce: to get away from physical or emotional abuse.";
            Motivations.Add(res);
            res = "Get a divorce: to marry a different person you've become infatuated with.";
            Motivations.Add(res);
            res = "Get a divorce: to spare your spouse from danger, because bad guys are after you.";
            Motivations.Add(res);
            res = "To fix up an old house: to sell it for a big profit.";
            Motivations.Add(res);
            res = "To fix up an old house: to have a decent place for you and your family to live, even though you don't have a lot of money.";
            Motivations.Add(res);
            res = "To fix up an old house: to turn it into a bed and breakfast.";
            Motivations.Add(res);
            res = "Kidnap someone: to keep them from being kidnapped or killed by some really evil person.";
            Motivations.Add(res);
            res = "Kidnap someone: to sell them into modern-day slavery.";
            Motivations.Add(res);
            res = "Kidnap someone: to get them to use their unique talents or skills to perform a certain task.";
            Motivations.Add(res);
            res = "Throw a party: to make friends because you're new in town or at the college.";
            Motivations.Add(res);
            res = "Throw a party: to have the opportunity to flirt with one or more of the people you invited.";
            Motivations.Add(res);
            res = "Throw a party: to surprise someone you love.";
            Motivations.Add(res);
            res = "Throw a party: to cheer up someone you love.";
            Motivations.Add(res);
            res = "Recover from an illness or an injury: to be able to attend an important event (like graduation)";
            Motivations.Add(res);
            res = "Recover from an illness or an injury: to be able to return to your old job.";
            Motivations.Add(res);
            res = "Recover from an illness or an injury: to be able to return to your chosen sport.";
            Motivations.Add(res);
            res = "Win a competition: to win glory for your school, your city, your country, or your planet.";
            Motivations.Add(res);
            res = "Win a competition: to feel proud and accomplished for once.";
            Motivations.Add(res);
            res = "Win a competition: to win the prize money you need for someone who needs it.";
            Motivations.Add(res);
            res = "Win a competition: to prove a racist or a sexist wrong";
            Motivations.Add(res);
            res = "Win a competition: to demonstrate to your child they can do anything they set their minds to.";
            Motivations.Add(res);
            res = "Procure top-secret info for a foreign government: to get revenge on your own country's government for a past wrong or perceived wrong.";
            Motivations.Add(res);
            res = "Procure top-secret info for a foreign government: to feel important.";
            Motivations.Add(res);
            res = "Procure top-secret info for a foreign government: to enjoy the thrill of danger.";
            Motivations.Add(res);
            res = "Run a marathon: to get in better shape.";
            Motivations.Add(res);
            res = "Run a marathon: to raise money for a cause.";
            Motivations.Add(res);
            res = "Run a marathon: to be able to brag about it.";
            Motivations.Add(res);
            res = "Become a soldier: to defend your country from invaders.";
            Motivations.Add(res);
            res = "Become a soldier: to get a steady paycheck.";
            Motivations.Add(res);
            res = "Become a soldier: To get a college education you can't afford otherwise.";
            Motivations.Add(res);
            res = "Have a baby: to give a kid an ideal childhood.";
            Motivations.Add(res);
            res = "Have a baby: to have someone to dress in cute little outfits.";
            Motivations.Add(res);
            res = "Have a baby: to have someone to take care of you when you're older.";
            Motivations.Add(res);
            res = "Have a baby: to give your parents a grandchild.";
            Motivations.Add(res);
            res = "Have a baby: to try to fix your troubled marriage or relationship.";
            Motivations.Add(res);
            res = "Have a baby: to try to replace your troubled marriage.";
            Motivations.Add(res);
            res = "Develop a vaccine: to save countless lives.";
            Motivations.Add(res);
            res = "Develop a vaccine: to be celebrated as a scientific genius.";
            Motivations.Add(res);
            res = "Develop a vaccine: to beat your rival, who's also working on a vaccine.";
            Motivations.Add(res);
            res = "Kick an addiction: to be able to hold down a job.";
            Motivations.Add(res);
            res = "Kick an addiction: to feel more self-respect.";
            Motivations.Add(res);
            res = "Kick an addiction: to gain more respect from your family.";
            Motivations.Add(res);
            res = "Kick an addiction: to save a lot of money.";
            Motivations.Add(res);
            res = "Kick an addiction: to enjoy life more.";
            Motivations.Add(res);
            res = "Learn a foreign language: to be prepared for an upcoming trip.";
            Motivations.Add(res);
            res = "Learn a foreign language: to further your career by adding it to your list of skills.";
            Motivations.Add(res);
            res = "Learn a foreign language: to read works by a particular writer -- or a particular document -- in its original language.";
            Motivations.Add(res);
            res = "Learn a foreign language: to communicate with a specific person in their own language.";
            Motivations.Add(res);
            res = "Get someone falsely convicted of a crime: to deflect suspicion from the real criminal.";
            Motivations.Add(res);
            res = "Get someone falsely convicted of a crime: to get revenge for what they did to you or your family.";
            Motivations.Add(res);
            res = "Start dating someone: to find someone to attend a wedding with, because it feels awkward to go alone.";
            Motivations.Add(res);
            res = "Start dating someone: to get over an ex by going out with someone new, even if it's not at all serious.";
            Motivations.Add(res);
            res = "Start dating someone: to take the first step toward finding a partner.";
            Motivations.Add(res);
            res = "Organize a successful festival: to attract more tourist dollars and help local businesses.";
            Motivations.Add(res);
            res = "Organize a successful festival: to make happy memories for friends and neighbors.";
            Motivations.Add(res);
            res = "Find a particular MacGuffin: to prove or to disprove a scientific or historical theory";
            Motivations.Add(res);
            res = "Find a particular MacGuffin: to use the object's magical powers for a specific purpose.";
            Motivations.Add(res);
            res = "Destroy a MacGuffin: to hide the truth about history or about a crime.";
            Motivations.Add(res);
            res = "Destroy a MacGuffin: to demonstrate your hatred of what the object represents.";
            Motivations.Add(res);
            res = "Destroy a MacGuffin: to keep the powerful object from falling into the wrong hands.";
            Motivations.Add(res);
            res = "Become immortal: to always look young.";
            Motivations.Add(res);
            res = "Become immortal: to get to travel the world and have countless adventures.";
            Motivations.Add(res);
            res = "Become immortal: to get to be with the one you love forever, since they're already immortal.";
            Motivations.Add(res);
            res = "Become immortal: to avoid imminent death from a disease.";
            Motivations.Add(res);
            res = "Track down a biological mother, father, or sibling you've never met before: to satisfy your curiosity about the past.";
            Motivations.Add(res);
            res = "Track down a biological mother, father, or sibling you've never met before: to satisfy your curiosity about whether you have much in common with them.";
            Motivations.Add(res);
            res = "Track down a biological mother, father, or sibling you've never met before: to develop a close family relationship now.";
            Motivations.Add(res);
            res = "Retire: to spend more time on hobbies or passions.";
            Motivations.Add(res);
            res = "Retire: to spend more time with grandkids or family.";
            Motivations.Add(res);
            res = "Retire: to move to a place you like better.";
            Motivations.Add(res);
            res = "Make contact with aliens: to make new friends, since you seem to have trouble getting along with people.";
            Motivations.Add(res);
            res = "Make contact with aliens: to learn about new technology from them.";
            Motivations.Add(res);
            res = "Start a revolution: to create a better world for your children.";
            Motivations.Add(res);
            res = "Start a revolution: to save those who are imprisoned, oppressed, or starving.";
            Motivations.Add(res);
            res = "Start a revolution: to bus a particular person out of jail.";
            Motivations.Add(res);
            res = "Start a revolution: to gain a lot of power for yourself in the new order.";
            Motivations.Add(res);
            res = "Find a missing person: to get them back into your life.";
            Motivations.Add(res);
            res = "Find a missing person: to make sure nothing terrible has happened to them.";
            Motivations.Add(res);
            res = "Find a missing person: to get key information from them.";
            Motivations.Add(res);
            res = "Find a missing person: to arrest them for their crimes.";
            Motivations.Add(res);
            res = "Get a tattoo: to mark a significant event or milestone.";
            Motivations.Add(res);
            res = "Get a tattoo: to honor a loved one.";
            Motivations.Add(res);
            res = "Get a tattoo: to feel like a badass.";
            Motivations.Add(res);
            res = "Get a tattoo: to fit in with a group.";
            Motivations.Add(res);
            res = "Get a tattoo: to rebel against authority.";
            Motivations.Add(res);
            res = "Reconcile with someone you fought with: to have them back in your life again, because you miss them.";
            Motivations.Add(res);
            res = "Reconcile with someone you fought with: to make sure they don't retaliate against you or someone you love.";
            Motivations.Add(res);
            res = "Reconcile with someone you fought with: to ask them to join you in a new cause.";
            Motivations.Add(res);
            res = "Set a building on fire: to kill a particular person or group of people in the building.";
            Motivations.Add(res);
            res = "Set a building on fire: to destroy damning evidence inside the building.";
            Motivations.Add(res);
            res = "Set a building on fire: to collect insurance money.";
            Motivations.Add(res);
            res = "Plant a garden: to have fresh organic produce because it's healthier.";
            Motivations.Add(res);
            res = "Plant a garden: to have fresh organic produce because you're a chef and it tastes better in recipes.";
            Motivations.Add(res);
            res = "Plant a garden: to have a source of food in case society completely breaks down.";
            Motivations.Add(res);
            res = "Become a church member: to strengthen your faith.";
            Motivations.Add(res);
            res = "Become a church member: to atone for past sins.";
            Motivations.Add(res);
            res = "Become a church member: to make new friends.";
            Motivations.Add(res);
            res = "Become a church member: to make a churchgoing relative happy.";
            Motivations.Add(res);
            res = "Become a church member: to make new business connections.";
            Motivations.Add(res);
            res = "Become a church member: to look like an upstanding citizen, because you're about to run for mayor.";
            Motivations.Add(res);
            res = "Go into hiding: to avoid the authorities who want to imprison and/or execute you.";
            Motivations.Add(res);
            res = "Go into hiding: to avoid your unpleasant family.";
            Motivations.Add(res);
            res = "Go into hiding: to avoid paying a large amount of money you owe.";
            Motivations.Add(res);
            res = "Save your marriage: to return the happiness you used to know with the person.";
            Motivations.Add(res);
            res = "Save your marriage: to avoid financial ruin.";
            Motivations.Add(res);
            res = "Save your marriage: to ensure a stable home life for your children.";
            Motivations.Add(res);
            res = "Save your marriage: to avoid feeling like you failed.";
            Motivations.Add(res);
            res = "Save your marriage: to avoid the judgment of your family.";
            Motivations.Add(res);
            res = "Travel to the other side of the World: to attend a funeral and to pay your last respects.";
            Motivations.Add(res);
            res = "Travel to the other side of the World: to attend a State funeral";
            Motivations.Add(res);
            res = "Travel to the other side of the World: to get amazine photos for your Instagram";
            Motivations.Add(res);
            res = "Travel to the other side of the World: to satisfy your hunger for grand adventures.";
            Motivations.Add(res);
            res = "Become famous: to become rich, which often comes with being famous.";
            Motivations.Add(res);
            res = "Become famous: to have a platform to talk about issues that matter most to you.";
            Motivations.Add(res);
            res = "Become famous: to get a huge ego boost.";
            Motivations.Add(res);
            res = "Break up a Couple: to get your family member to marry someone of a higher status.";
            Motivations.Add(res);
            res = "Break up a Couple: to get one of them to marry you instead.";
            Motivations.Add(res);
            res = "Break up a Couple: to ruin the happiness of one of them, because you harbor a grudge.";
            Motivations.Add(res);
            res = "Get two people to fall in love and get married: to make your friend or family member happy.";
            Motivations.Add(res);
            res = "Get two people to fall in love and get married: to get them to pass down their supernatural powers... and give birth to an even more powerful child.";
            Motivations.Add(res);
            res = "Get two people to fall in love and get married: to get the grandchildren you want.";
            Motivations.Add(res);
            res = "Get two people to fall in love and get married: to further your reputation as a talented matchmaker, because it makes you feel important.";
            Motivations.Add(res);
            res = "Change a law: to further your own business interests.";
            Motivations.Add(res);
            res = "Change a law: to bring about more equality for yourself.";
            Motivations.Add(res);
            res = "Change a law: to bring about more equality for others.";
            Motivations.Add(res);
            res = "Change a law: to be able to enjoy yourself more.";
            Motivations.Add(res);

        }




    }
}
